CREATE EXTENSION IF NOT EXISTS "pgcrypto"; -- Para gen_random_uuid()

CREATE TABLE "Users" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "code" UUID NOT NULL DEFAULT gen_random_uuid(),
    "username" VARCHAR(63) NOT NULL UNIQUE,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "password_salt" VARCHAR(32) NOT NULL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now())
);

CREATE TABLE "Category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now())
);

CREATE TABLE "Assets" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "code" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,        -- Ej: "NVIDIA"
    "symbol" VARCHAR(255) NOT NULL,      -- Ej: "NVDA"
    "ticker" VARCHAR(255),               -- Para consulta a API externa
    "currency" VARCHAR(3) NOT NULL,      -- USD, COP, BTC...
    "category_id" INTEGER NOT NULL,
    "total_units" DECIMAL NOT NULL,      -- unidades actuales (stock)
    "current_value" DECIMAL,             -- Solo usado si es valor manual (CDT, etc.)
    "invested_total" DECIMAL NOT NULL DEFAULT 0, -- Total invertido en la moneda del activo
    "auto_pricing_enabled" BOOLEAN NOT NULL DEFAULT TRUE,  -- Si se usa API externa para precios
    "price_source" VARCHAR(255),         -- Ej: 'yahoo', 'coingecko'
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()),
    FOREIGN KEY ("user_id") REFERENCES "Users"("id"),
    FOREIGN KEY ("category_id") REFERENCES "Category"("id")
);

CREATE TABLE "Transactions" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "code" UUID NOT NULL DEFAULT gen_random_uuid(),
    "asset_id" BIGINT NOT NULL,
    "type" VARCHAR(50) NOT NULL,         -- BUY / SELL / DEPOSIT / WITHDRAW
    "units" DECIMAL NOT NULL,            -- unidades compradas/vendidas
    "total" DECIMAL NOT NULL,            -- valor total de la operación
    "fee_total" DECIMAL DEFAULT 0,       -- comisiones
    "currency" VARCHAR(3) NOT NULL,      -- en qué moneda se hizo la operación
    "note" TEXT,                         -- opcional: "compra mensual"
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()),
    FOREIGN KEY ("asset_id") REFERENCES "Assets"("id") ON DELETE CASCADE
);

INSERT INTO "Category" (id, name) VALUES
(1, 'CASH'),
(2, 'SAVINGS_ACCOUNT'),
(3, 'FIXED_INCOME'),
(4, 'STOCK'),
(5, 'ETF'),
(6, 'CRYPTO'),
(7, 'MUTUAL_FUND'),
(8, 'COMMODITY'),
(9, 'CURRENCIES'),
(10,'OTHER');
